apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kalink-studio
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
    - hosts:
        - kalink.ch
        - www.kalink.ch
      secretName: kalink-studio-tls
  rules:
    - host: www.kalink.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kalink-studio
                port:
                  number: 3000
