---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kalink-studio-staging-basic-auth
  namespace: staging
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    auth: AgBpdKp2KfcCiwXq7wtg+KWqRHDp7gsrpIIj8qdyCXUx2DAAZIEP7FEtW/vE1ZS5wBzYRuYQBIxeRrE/h+nHG1+uvg37O/iT8bUfUAzhuZs0WaY6XkfnNSdoMA6DY+Rscj5s3U0VtxDGyO9Bv6uBneBhuPSiJcgqHfKsx6XIan5HNHWwWKqTEfCuJglxl6YnnEqfzqg/tm8O/MRoouXRHhEP4m2yvp3c9ak5dQLczS8n7vHrmkSwmewU0uR4sTl1yA2AVhFxbmgktlrHlwAmnJju99YK2mnAoRKjDhBcnvl0vHfy3ZuMJKAGoZ5iaU2COJ6BPLtLhLNwryxJdz9kP3vJ9XZQGlbn0Wh8xG149dXSqEmI/dWcJb5zeWJTXBr1cT4e/fdtbaaxeNw6BrFvDE61VasUWWdtrBWvBnPPE2SzXw6uby/PIGaS5k2UV9+S1FXffmt48PvzgjbCiR8P6aIKmjroHTf11tgb5I2QSimivIT8M4lxmNaNstioxqb+hpqEaItIemTViW2wOhKBs4q+mmOiWZKewnvbrRMuCvtU0tmvc1HRqbTerRDoLgmWcn8bi+0DaPqrDHaIzxCarNl+6x5FQXFoBKl1F0V73Z9RSNSYbC5yMrh5S12pGwlt32MpwrsUBbL27okKZ3ATvV7Dz9FBIvo1iHJn13Lh6fCxeskSsxOKANjYUThWYPCnPAAdA15g/KSMWpLOWKJ9MNh3QrEWgZ5znrZsVdUaaXvcTCqE8H+3qLihv+ST1da+KHkY/CNJDX6pU/LzIgAc/tfDmi5rThsFVQ==
  template:
    metadata:
      name: kalink-studio-staging-basic-auth
      namespace: staging
