apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kalink-studio
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - staging.kalink.ch
      secretName: kalink-studio-staging-tls
  rules:
    - host: staging.kalink.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kalink-studio
                port:
                  number: 3000
