apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - sealedsecret.yaml
  - basic-auth-sealedsecret.yaml
  - migration-job.yaml

patches:
  - path: ingress-patch.yaml
  - path: hpa-patch.yaml
  - path: sealedsecret-patch.yaml

images:
  - name: ghcr.io/kalink-studio/kalink
    newTag: 914ada7

replicas:
  - name: kalink-studio
    count: 1
